# Generated by Django 5.1.5 on 2025-01-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=70)),
                ('asunto', models.CharField(max_length=70)),
                ('contenido', models.TextField()),
                ('fecha_recibido', models.DateTimeField()),
                ('etiqueta', models.CharField(choices=[('legitimo', 'Legítimo'), ('malicioso', 'Malicioso')], max_length=10)),
                ('es_phishing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhishingReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.correoelectrico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='correoelectrico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.usuario'),
        ),
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_seguridad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=5)),
                ('notificacion', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.usuario')),
            ],
        ),
    ]
