# Generated by Django 5.1.5 on 2025-01-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoelectrico',
            name='fecha_recibido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
